import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://freepngimg.com/thumb/car/4-2-car-png-hd-thumb.png",
    title: "Tesla Model S",
    star: <AiFillStar className="rating-star" />,
    reviews: "(150 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Tesla",
    color: "blue",
    category: "electric",
    seller :"abc",
    number:"123",
    
  },
  {
    img: "https://freepngimg.com/thumb/car/1-2-car-png-picture-thumb.png",
    title: "BMW X5",
    star: <AiFillStar className="rating-star" />,
    reviews: "(200 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Ford",
    color: "red",
    category: "sports",
    seller :"abd",
    number:"1234",
  },
  {
    img: "https://freepngimg.com/thumb/car/3-2-car-free-download-png-thumb.png",
    title: "Tesla Model S",
    star: <AiFillStar className="rating-star" />,
    reviews: "(180 reviews)",
    prevPrice: "$140,00",
newPrice: "50",
    company: "Chevrolet",
    color: "blue",
    category: "sports",
    seller :"abc",
    number:"123",
  },
  {
    img: "https://freepngimg.com/thumb/car/1-2-car-png-picture-thumb.png",
    title: "Toyota Prius",
    star: <AiFillStar className="rating-star" />,
    reviews: "(250 reviews)",
    prevPrice: "$140,00",
newPrice: "100",
    company: "Toyota",
    color: "green",
    category: "hybrid",
    seller :"abcy",
    number:"1238",
  },
  {
    img:"https://freepngimg.com/thumb/audi/2-black-r8-audi-png-car-image-thumb.png",
    title: "Toyota Prius",
    star: <AiFillStar className="rating-star" />,
    reviews: "(220 reviews)",
    prevPrice: "$140,00",
newPrice: "150",
    company: "Honda",
    color: "black",
    category: "sedan",
    seller :"abc",
    number:"123",
  },
  {
    img: "https://freepngimg.com/thumb/car/7-2-car-free-png-image-thumb.png",
    title: "BMW X5",
    star: <AiFillStar className="rating-star" />,
    reviews: "(190 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "BMW",
    color: "white",
    category: "SUV",
    seller :"abd",
    number:"1234",
  },
  {
    img: "https://freepngimg.com/thumb/car/6-2-car-png-file-thumb.png",
    title: "Toyota Prius",
    star: <AiFillStar className="rating-star" />,
    reviews: "(210 reviews)",
    prevPrice: "$140,00",
newPrice: "150",
    company: "Audi",
    color: "black",
    category: "SUV",
    seller :"abc",
    number:"123",
  },
  {
    img: "https://freepngimg.com/thumb/lamborghini/1-2-lamborghini-png-thumb.png",
    title: "Mercedes-Benz",
    star: <AiFillStar className="rating-star" />,
    reviews: "(230 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Mercedes-Benz",
    color: "silver",
    category: "sedan",
    seller :"abcu",
    number:"1239",
  },
  
]

export default data;
